apiVersion: sample.stepflow/v1alpha1
kind: Sample
metadata:
  labels:
    app.kubernetes.io/name: kubernetes-controller
    app.kubernetes.io/managed-by: kustomize
  name: sample-sample
spec:
  # TODO(user): Add fields here
