name: Tests

on:
  push:
    paths:
      - 'kubernetes-controller/**'
  pull_request:
    paths:
      - 'kubernetes-controller/**'

jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kubernetes-controller/
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./kubernetes-controller/go.mod

      - name: Running Tests
        run: |
          go mod tidy
          make test
